version: "2"
services:
  gateway-manager:
    build: .
    environment:
      - MONGO_URI=mongodb://mongodb:27017/express-rest-es2017-boilerplate
      - NODE_ENV=development
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
